# Generated by Django 5.2.10 on 2026-01-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
