# Generated by Django 5.2.10 on 2026-01-20 17:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Universities', '0002_universities_delete_university'),
        ('Users', '0002_user_email_user_role_user_username_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cps_number', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('role', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('admin', 'Admin'), ('super_admin', 'Super Admin'), ('developer', 'Developer')], max_length=20)),
                ('password_hash', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('qr_code_data', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universities.universities')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['cps_number'], name='Users_users_cps_num_1756b1_idx'),
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['phone_number'], name='Users_users_phone_n_0e57eb_idx'),
        ),
    ]
