# Generated by Django 5.2.10 on 2026-01-20 17:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Universities', '0002_universities_delete_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('duration_type', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('semester', 'Semester')], max_length=20)),
                ('duration_days', models.IntegerField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=2, max_digits=12, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Universities.universities')),
            ],
        ),
    ]
